// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCym17rxK0Pn9L18l2h2W4aJXjfETAf6Lk',
    appId: '1:883820804034:web:44cc7534adfea0c481c85b',
    messagingSenderId: '883820804034',
    projectId: 'e-ehson',
    authDomain: 'e-ehson.firebaseapp.com',
    storageBucket: 'e-ehson.firebasestorage.app',
    measurementId: 'G-WRRN56L2K5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIIt6RH_G47nrQzYh85YsQKU2Vbr7f0DM',
    appId: '1:883820804034:android:5ece1c36f01e971681c85b',
    messagingSenderId: '883820804034',
    projectId: 'e-ehson',
    storageBucket: 'e-ehson.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6HFuIfaBr4Lmfs7AUNh6BL9Gekx9t-YY',
    appId: '1:883820804034:ios:3833353c0205b03e81c85b',
    messagingSenderId: '883820804034',
    projectId: 'e-ehson',
    storageBucket: 'e-ehson.firebasestorage.app',
    iosBundleId: 'com.example.aidokon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6HFuIfaBr4Lmfs7AUNh6BL9Gekx9t-YY',
    appId: '1:883820804034:ios:3833353c0205b03e81c85b',
    messagingSenderId: '883820804034',
    projectId: 'e-ehson',
    storageBucket: 'e-ehson.firebasestorage.app',
    iosBundleId: 'com.example.aidokon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCym17rxK0Pn9L18l2h2W4aJXjfETAf6Lk',
    appId: '1:883820804034:web:1830f90ac76dd1ed81c85b',
    messagingSenderId: '883820804034',
    projectId: 'e-ehson',
    authDomain: 'e-ehson.firebaseapp.com',
    storageBucket: 'e-ehson.firebasestorage.app',
    measurementId: 'G-J1S6KEETD0',
  );

}